### ISSUE TITLE
Better handle of template `tailwind.css` file write location

### ISSUE THREAD

**Issue by kevinmarrec** [Atinux/nuxt-tailwindcss#1]
Assuming https://nuxtjs.org/api/configuration-dir, user could have custom assets directory name, so we need to take this into account.

First step is to use `this.options.dir.assets` to get the right `assets` folder.
Then we need to add a module option so user can customize which folder in his `assets` folder is the one where he stores css (could be `assets/css`, `assets/styles` or even `assets/xxx` where user alrady have some css files)

It should end up in something like 
```js
path.join('@', this.options.dir.assets, moduleOptions.OPTION_NAME || 'css', 'tailwind.css')
```

**Comment by Atinux** [comment]
Thanks @kevinmarrec 

It is now using `this.options.dir.assets` and the path is configurable with `tailwindcss.cssPath` now :)
https://github.com/Atinux/nuxt-tailwindcss/blob/master/lib/module.js#L14
