### ISSUE TITLE
[Feature request] option to custom tailwind config path

### ISSUE THREAD

**Issue by kevinmarrec** [Atinux/nuxt-tailwindcss#2]
Provide an option to customize the tailwind config path, for example `~/config/tailwind.js` instead of `~/tailwind.config.js`.

**Comment by kevinmarrec** [comment]
If postcss tailwind plugin accept an object directly containing config instead of path of the config, we can also do things different depending on type of the option.

```js
export default {
   tailwind : {
    config: './config/tailwind.js'
  }
}
```

OR 

```js
export default {
  tailwind: {
    config: {
      theme: {
        ...
      },
      variants: {
        ...
       }
    }
  }
}
```

**Comment by Atinux** [comment]
Thanks @kevinmarrec 

it's now possible to give `tailwindcss.configPath` key directly :)
